from workflow.ai_context import build_context
from workflow.memory import save_session, save_summary, save_meta
from workflow.rag import get_rag, update_rag_with_session
from workflow.ai_providers.claude import ClaudeProvider
from workflow.ai_providers.opencode import OpenCodeProvider
from workflow.ai_providers.flow import FlowProvider
from workflow.config import load_config, load_effective_config
from workflow.projects import get_current_project_default_repo
from pathlib import Path
import typer

def get_ai_provider():
    """Get the configured AI provider"""
    config = load_effective_config()
    ai_config = config.get("ai", {})
    provider_name = ai_config.get("provider", "claude")
    
    if provider_name == "flow":
        return FlowProvider()
    elif provider_name == "opencode":
        return OpenCodeProvider()
    elif provider_name == "claude":
        return ClaudeProvider()
    else:
        print(f"⚠️  Unknown AI provider '{provider_name}', falling back to Claude")
        return ClaudeProvider()

def launch_ai_session(issue):
    print("🔍 Starting AI command...")
    if not issue:
        typer.echo("No current task set. Use 'wf start' to begin a task.")
        return
    
    print(f"📋 Found current task: {issue.key}")
    
    # Get default repository path for repo-specific instructions
    repo_path = get_current_project_default_repo()
    
    # Use RAG-enabled AI session
    try:
        print("🤖 Initializing AI session with RAG...")
        
        # Build context with RAG
        initial_query = f"project overview structure commands for {issue.title}"
        context = build_context(issue, initial_query, repo_path)
        
        print("🔄 Starting AI provider...")
        provider = get_ai_provider()
        transcript = provider.run(context, issue)
        print("💬 AI session completed")
        save_session(issue, transcript)
        save_meta(issue, provider.name)
        
        # Read the summary that was already generated by the provider
        if issue and hasattr(issue, 'key'):
            task_dir = Path.home() / ".wf" / "tasks" / issue.key.lower()
            summary_file = task_dir / "summary.txt"
            if summary_file.exists():
                summary = summary_file.read_text()
                save_summary(issue, summary)
                print("📝 Summary saved")
            else:
                print("⚠️  No summary file found")
        
        # Extract learnings from session and update RAG
        if transcript:
            try:
                print("🧠 Extracting session learnings...")
                learnings_prompt = f"""
Based on this AI session transcript, extract key learnings about the project that would be helpful for future sessions:

TRANSCRIPT:
{transcript}

Please provide:
1. Key architectural patterns discovered
2. Important code locations or files identified
3. Common issues or solutions found
4. Development workflow insights
5. Any other project-specific knowledge gained

Format as a concise summary:
"""
            
                learnings = provider.run(learnings_prompt, issue)
                update_rag_with_session(issue.key, transcript, learnings)
                print("📚 RAG context updated with session learnings")
            except Exception as e:
                print(f"⚠️  Could not update RAG context: {e}")
                import traceback
                traceback.print_exc()
        
        print("✅ AI session completed")
    except Exception as e:
        typer.echo(f"❌ Error in AI session: {e}")
        import traceback
        traceback.print_exc()
    
    print("✅ AI session workflow completed")
