class Issue:
    def __init__(self, key, title, description, updated=None):
        self.key = key
        self.title = title
        self.description = description
        self.updated = updated

class TaskBackend:
    def get(self, key) -> Issue: ...
    def get_or_create(self, q) -> Issue | None: ...
    def select_interactively(self, include_others=False) -> Issue | None: ...
    def move_to_in_progress(self, issue, custom_fields=None): ...
    def move_to_done(self, issue): ...
    def move_to_review(self, issue): ...
    def create_issue(self, summary, description, issue_type="Task", project_key=None) -> Issue | None: ...
